"""fleet + gps_points

Revision ID: 24a04e22dd61
Revises: 8e1582729149
Create Date: 2026-07-14 01:23:32.930723
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '24a04e22dd61'
down_revision: str | None = '8e1582729149'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('reg_no', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', name='bus_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_reg_no'), 'buses', ['reg_no'], unique=True)
    op.create_table('gps_points',
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('matched_route_pct', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_points_bus_id'), 'gps_points', ['bus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_points_bus_id'), table_name='gps_points')
    op.drop_table('gps_points')
    op.drop_index(op.f('ix_buses_reg_no'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
