"""Trips, routes, stops — the trip spine (spec §6).

Revision ID: c4d8e1f60a35
Revises: b7f3c1a9d2e4
Create Date: 2026-07-23

Hand-written rather than autogenerated: the two partial unique indexes on
`trips` (one live trip per bus, one per helper) are Postgres-specific and
alembic's autogenerate does not round-trip `postgresql_where` reliably.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c4d8e1f60a35"
down_revision: str | None = "b7f3c1a9d2e4"
branch_labels: str | None = None
depends_on: str | None = None

_TIMESTAMPS = (
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
)


def upgrade() -> None:
    op.create_table(
        "stops",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        *_TIMESTAMPS,
    )

    # Declared inline rather than created separately: create_table emits the
    # CREATE TYPE ahead of the table, which keeps this migration runnable
    # offline (`alembic upgrade head --sql`) — an explicit .create(checkfirst=True)
    # needs a live connection to check against.
    op.create_table(
        "routes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="route_direction"),
            nullable=False,
        ),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        *_TIMESTAMPS,
        sa.UniqueConstraint("name", "direction", name="uq_routes_name_direction"),
    )

    op.create_table(
        "route_stops",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "route_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("routes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "stop_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("stops.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("scheduled_offset_min", sa.Integer(), nullable=True),
        *_TIMESTAMPS,
        sa.UniqueConstraint("route_id", "seq", name="uq_route_stops_route_seq"),
        sa.UniqueConstraint("route_id", "stop_id", name="uq_route_stops_route_stop"),
    )
    op.create_index("ix_route_stops_route_id", "route_stops", ["route_id"])
    op.create_index("ix_route_stops_stop_id", "route_stops", ["stop_id"])

    op.create_table(
        "trips",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "route_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("routes.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "bus_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("buses.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "helper_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("helpers.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("scheduled", "live", "completed", "cancelled", name="trip_status"),
            nullable=False,
            server_default="scheduled",
        ),
        *_TIMESTAMPS,
    )
    op.create_index("ix_trips_route_id", "trips", ["route_id"])
    op.create_index("ix_trips_bus_id", "trips", ["bus_id"])
    op.create_index("ix_trips_helper_id", "trips", ["helper_id"])
    op.create_index("ix_trips_service_date_status", "trips", ["service_date", "status"])

    # The rules that make "one bus, one live trip" true rather than hoped for.
    # A check-then-insert in Python loses to a double-tap of the Start button;
    # a partial unique index does not.
    op.create_index(
        "uq_trips_one_live_per_bus",
        "trips",
        ["bus_id"],
        unique=True,
        postgresql_where=sa.text("status = 'live'"),
    )
    op.create_index(
        "uq_trips_one_live_per_helper",
        "trips",
        ["helper_id"],
        unique=True,
        postgresql_where=sa.text("status = 'live'"),
    )


def downgrade() -> None:
    op.drop_table("trips")
    op.drop_table("route_stops")
    op.drop_table("routes")
    op.drop_table("stops")
    postgresql.ENUM(name="trip_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="route_direction").drop(op.get_bind(), checkfirst=True)
