"""Emit a boarding-code fixture for the Flutter test suite.

The helper app verifies codes with its own Dart implementation of the signing
layout. Two implementations of one format drift silently: nothing fails until a
real passenger is refused at a real door, and the only diagnostic is "invalid
ticket".

So `unitrack-helper/test/qr_verifier_test.dart` verifies a code that **this**
signer produced, rather than one Dart signed for itself. A test that signs and
verifies with the same code proves the code is self-consistent and nothing
about the pairing.

    uv run python -m scripts.dev_qr_fixture

Paste the output over the `_fixture` record in that test. If the payload layout
ever changes, regenerating this is the smallest part of the job — every ticket
already issued would need reissuing too.
"""

from app.services.boarding import (
    QrPayload,
    build_qr,
    generate_keypair,
    new_nonce,
)

# Fixed rather than "now", so the test is not a clock away from failing.
FIXED_SLICE = 56163406
TICKET_ID = "8626e7c2-4b60-42a4-be68-ce877496c9c0"


def main() -> None:
    private, public = generate_keypair()
    _, other_public = generate_keypair()

    code = build_qr(
        private,
        QrPayload(
            ticket_id=TICKET_ID,
            passenger_count=1,
            time_slice=FIXED_SLICE,
            nonce=new_nonce(),
        ),
    )

    print("// Generated by unitrack-backend/scripts/dev_qr_fixture.py")
    print("const _fixture = (")
    print(f"  ticketId: '{TICKET_ID}',")
    print(f"  publicKey: '{public}',")
    print(f"  slice: {FIXED_SLICE},")
    print(f"  code: '{code}',")
    print(");")
    print()
    print(f"const _otherPublicKey = '{other_public}';")


if __name__ == "__main__":
    main()
